return {
	{
		"nvim-treesitter/nvim-treesitter",
		opts = {
			highlight = { enable = true },
			indent = { enable = true },
			ensure_installed = {
				"cmake",
				"cpp",
				"gitignore",
				"go",
				"graphql",
				"http",
				"java",
				"scss",
				"sql",
				"json",
				"javascript",
				"typescript",
				"tsx",
				"yaml",
				"html",
				"css",
				"markdown",
				"markdown_inline",
				"bash",
				"vim",
				"lua",
				"dockerfile",
			},
			build = ":TSUpdate",
			event = { "BufReadPre", "BufNewFile" },
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
		},
	},
}
