name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: alpine-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ steps.version.outputs.version }}
            draft: false
            prerelease: false
